version: 2.1

defaults: &defaults
  working_directory: ~/competency-acl
  docker:
    - image: cimg/node:lts

orbs:
  cyber4all: cyber4all/orb@2.1.8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Remove Prepare Script
          command: npm pkg delete scripts.prepare
      - run:
          name: Install dependencies
          command: npm install --ignore-scripts
      - run:
          name: Build package
          command: npm run build
      - run:
          name: Run tests
          command: npm test
      - store_test_results:
          path: ./reports/junit.xml
      - persist_to_workspace:
          root: ./
          paths:
            - ./package.json
            - ./lib
 
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/competency-acl
      - run:
          name: Expose NPM Key
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/competency-acl/.npmrc
      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              ignore: /releases/

  build-test-and-publish:
    when:
      equal: [releases, << pipeline.git.branch >>]
    jobs:
      - build
   
      - cyber4all/release:
          requires:
            - build
          context: [Github]
          tag: "$(jq -r '.version' package.json)"
      
      - publish:
          requires:
            - build
            - cyber4all/release
    
